# -*- coding: utf-8 -*-
"""Copy of Weather.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q_lhTZmvH9QkGDvYu-kQoDTTI4zEFzF4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

weather_data=pd.read_csv('/content/1. Weather Data.csv')

weather_data.head()

weather_data.describe()

weather_data.info()

weather_data.shape

weather_data.isnull().sum()

weather_data.columns

all_weather=pd.DataFrame(weather_data['Weather'].unique())
all_weather

weather=weather_data['Weather'].value_counts()
weather

"""# **EDA:**

**Clear Weather**
"""

clear_weather=weather_data[weather_data.Weather=='Clear']
clear_weather

plt.plot(clear_weather['Temp_C'].values, color='gold')
plt.title('Temperature on Clear Weather Days')
plt.xlabel('Index')
plt.ylabel('Temperature (°C)')
plt.grid(True)
plt.show()

"""**Find the number of times when the "wind speed was exactly 4 km/h".**"""

wind_speed=weather_data[weather_data['Wind Speed_km/h']==4]
wind_speed

x = wind_speed['Weather'].value_counts().reset_index()
x.columns = ['Weather', 'Count']
x

plt.figure(figsize=(12,6))
sns.barplot(data=x, x='Weather', y='Count')
plt.title('Weather Types When Wind Speed = 4 km/h')
plt.xticks(rotation=45)
plt.show()

weather_data.groupby('Weather').min()

weather_data.groupby('Weather').max()

#Show all the records where Weather condition is Fog
weather_data[weather_data['Weather']=='Fog']

#Find all the instances when 'Weather is clear' or 'Visibility is above 40
weather_data[(weather_data['Weather'] == 'Clear') | (weather_data['Visibility_km'] > 40)]

#Weather is clear" and "relative Humidity is greater tha 50
weather_data[(weather_data['Weather']=='Clear') & (weather_data['Rel Hum_%']>50)]

pip install ydata-profiling

from ydata_profiling import ProfileReport

pip install "ydata-sdk[text]"

profile = ProfileReport(weather_data, title="EDA Report", explorative=True)

profile.to_file("report.html")